config/routes.rb
Rails.application.routes.draw do
  resources :words
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # the root "/" of the website will call the Pages controller, "home" action/method.
  root to: 'pages#home'
  
  # the "/about" GET request will call the Pages controller, "about" action/method.
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end


# the method/action name here in the controller needs to match with a view file.
#  eg. the 'about' action --> app/views/pages/about.html.erb
#  and also a route in config/routes file first (config/routes.rb)

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :definition, :sentence, :notes, :tags, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemBox</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,400i,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <!-- Navbar -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <!-- Using the Rails way below    
          <a href="/" class="navbar-brand"><i class="fa fa-cube"></i> MemBox</a>
          -->
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-cube"></i> MemBox
          <% end %>
          <!-- This adds the lines in the do loop to an anchor/link -->
          
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            
            <!-- Rails way below  
              <li><a href="/about">About</a></li> 
            -->
            <li><%= link_to "About", about_path %></li> 
            <li><%= link_to "My Words List", words_path %></li>
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About page</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, mollitia, aspernatur illo voluptatum incidunt molestias rem repellat ut nesciunt tempora labore culpa corporis quos molestiae nihil eaque dignissimos. Eaque, alias.</p>
</div>

app/views/pages/home.html.erb
<div class="container-fluid home-callout text-center">
  <h1>Welcome to MemBox</h1>
  <h3>A resource to help you on your language learning journey.</h3>
</div>

app/views/words/_form.html.erb
<%= form_for(word) do |f| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :word %>
    <%= f.text_field :word, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :definition %>
    <%= f.text_field :definition, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :sentence %>
    <%= f.text_area :sentence, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :tags %>
    <%= f.text_field :tags, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :status %>
    <%= f.text_field :status, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<div class="container">
  <h1>Editing Word</h1>
  
  <%= render 'form', word: @word %>
  
  <%= link_to 'Show', @word %> |
  <%= link_to 'Back', words_path %>
</div>

app/views/words/index.html.erb
<div class="container">
  
  <p id="notice"><%= notice %></p>
  
  <h1>Words</h1>
  
  <table class="table">
    <thead>
      <tr>
        <th>Word</th>
        <th>Definition</th>
        <th>Sentence</th>
        <th>Notes</th>
        <th>Tags</th>
        <th>Status</th>
        <th>Created Date</th>
        <th>Updated Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @words.each do |word| %>
        <tr>
          <td><%= word.word %></td>
          <td><%= word.definition %></td>
          <td><%= word.sentence %></td>
          <td><%= word.notes %></td>
          <td><%= word.tags %></td>
          <td><%= word.status %></td>
          <td><%= word.created_at.to_date %></td>
          <td><%= word.updated_at.to_date %></td>
          <td><%= link_to 'View', word, class: 'btn btn-info' %></td>
          <td><%= link_to 'Edit', edit_word_path(word), class: 'btn btn-warning' %></td>
          <td><%= link_to 'Delete', word, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Word', new_word_path, class: 'btn btn-primary' %>
  
</div>

app/views/words/new.html.erb
<div class="container">
  <h1>New Word</h1>
  
  <%= render 'form', word: @word %>
  
  <%= link_to 'Back', words_path %>
</div>

app/views/words/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Word:</strong>
    <%= @word.word %>
  </p>
  
  <p>
    <strong>Definition:</strong>
    <%= @word.definition %>
  </p>
  
  <p>
    <strong>Sentence:</strong>
    <%= @word.sentence %>
  </p>
  
  <p>
    <strong>Notes:</strong>
    <%= @word.notes %>
  </p>
  
  <p>
    <strong>Tags:</strong>
    <%= @word.tags %>
  </p>
  
  <p>
    <strong>Status:</strong>
    <%= @word.status %>
  </p>
  
  <p>
    <strong>Created:</strong>
    <%= @word.created_at %>
  </p>
  
  <p>
    <strong>Updated:</strong>
    <%= @word.updated_at %>
  </p>
  
  <%= link_to 'Edit', edit_word_path(@word) %> |
  <%= link_to 'Back', words_path %>
</div>